name: Build CI

on:
  workflow_run:
    workflows: [Security CI]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t hmtonywang/dictionary-api-server:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: 'hmtonywang/dictionary-api-server:${{ github.sha }}'
        format: 'sarif'
        output: 'build-trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'build-trivy-results.sarif'
