name: Build CI

on:
  workflow_run:
    workflows: [Test CI]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: yarn build
