name: Test CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:18-alpine
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run test
      run: yarn test
      env:
        REDIS: redis://redis:6379
