name: Test CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:18-alpine
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn install --production --frozen-lockfile
    - name: Run test
      run: yarn test
      env:
        REDIS: redis://localhost:6379
